### ISSUE TITLE
New-GuacamoleUser: Password not set

### ISSUE THREAD

**Issue by schulz-alexander** [hvoges/PoshGuacamole#1] opened 2022-02-17 13:40 UTC
**Problem:**
If I create a new user with ```New-GuacamoleUser -Username testuser -Password testpass``` then the password ist not set and I can not login into guacamole

**Solution**
Change in New-GuacamoleUser.ps1 on line 73 from
```Password = $Password```
to
```password = $Password```

**Comment by hvoges** [comment] 2022-02-17 15:16
Thank you for your comment. The issue is fixed now.

**Closed as completed by hvoges** 2022-02-17 15:16 UTC
